-- AI Router settings use the existing public.ai_settings table.
-- Supabase is accessed only from the TanStack Start server with the
-- server-only service role key. No Supabase Project URL or Anon Key is
-- required in the browser.
